/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNode */

#ifndef _Included_JNode
#define _Included_JNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNode
 * Method:    start
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNode_start
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
