/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNode */

#ifndef _Included_JNode
#define _Included_JNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNode
 * Method:    start
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNode_start
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     JNode
 * Method:    fciArgCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_JNode_fciArgCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JNode
 * Method:    fciArgIsNumber
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_JNode_fciArgIsNumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JNode
 * Method:    fciArgIsFunction
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_JNode_fciArgIsFunction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JNode
 * Method:    fciArgNumberValue
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_JNode_fciArgNumberValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JNode
 * Method:    fciArgFunctionAsPersistentHandle
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_JNode_fciArgFunctionAsPersistentHandle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JNode
 * Method:    fciArgFunctionCallWithNoArguments
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JNode_fciArgFunctionCallWithNoArguments
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JNode
 * Method:    fciSetReturnNumberValue
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_JNode_fciSetReturnNumberValue
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     JNode
 * Method:    functionHandleCallWithNoArguments
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNode_functionHandleCallWithNoArguments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JNode
 * Method:    functionPersistentHandleDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNode_functionPersistentHandleDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
